;
; C64 Kernal Routines (refer to the Commodore
; 64 Programmer's Reference Guide)
;

.include "config.inc"

CHROUT      =       $FFD2
STOP        =       $FFE1
SETLFS      =       $FFBA
SETNAM      =       $FFBD
CLALL       =       $FFE7
OPEN        =       $FFC0
CHRIN       =       $FFCF
CHKIN       =       $FFC6
CHKOUT      =       $FFC9
GETIN       =       $FFE4
CLRCHN      =       $FFCC
CLOSE       =       $FFC3
LOAD        =       $FFD5
SAVE        =       $FFD8
IOINIT      =       $FF84

